- include: packages.yml
- include: user.yml

- name: Clone Zuul repository
  become: yes
  git:
    repo=https://git.openstack.org/openstack-infra/zuul
    dest=/opt/zuul

- name: Install Zuul
  become: yes
  pip:
    name=/opt/zuul

- include: config.yml

- name: Create zuul service files
  become: yes
  copy:
    src="{{ item.src }}"
    owner=root
    group=root
    mode=0755
    dest="{{ item.dest }}"
  with_items:
    - { src: 'zuul-server.service', dest: '/etc/systemd/system/zuul-server.service' }
    - { src: 'zuul-merger.init', dest: '/etc/init.d/zuul-merger' }
    - { src: 'zuul-launcher.init', dest: '/etc/init.d/zuul-launcher' }

- name: Start zuul-server
  become: yes
  service:
    name=zuul-server
    state=started
    enabled=yes

- include: layout.yml
  when: zuul_layout is defined
