- name: Install packages
  become: yes
  become_method: sudo
  yum:
    name="{{ item }}"
  with_items:
    - 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
    - python-pip
    - python-lockfile
    - python-paramiko
    - python-daemon
    - logrotate

- name: Install pip packages
  become: yes
  become_method: sudo
  pip:
    name="{{ item }}"
  with_items:
    - 'webob'
    - 'paste'

- name: Add 'zuul' group
  become: yes
  become_method: sudo
  group:
    name=zuul
    state=present

- name: Add 'zuul' user
  become: yes
  become_method: sudo
  user:
    name=zuul
    shell=/bin/bash
    group=zuul
    state=present

- name: Retrieve Zuul
  become: yes
  become_method: sudo
  git:
    repo=https://git.openstack.org/openstack-infra/zuul
    dest=/opt/zuul

- name: Install Zuul
  become: yes
  become_method: sudo
  pip:
    name=/opt/zuul

- name: Deploy zuul.conf
  template:
    src=zuul.conf.j2
    dest=/etc/zuul/zuul.conf
    mode=0755

- name: Create zuul directories
  become: yes
  become_method: sudo
  file:
    path="{{ item }}"
    state=directory
    owner=zuul
    group=zuul
    mode=0755
  with_items:
    - '/var/log/zuul'
    - '/var/run/zuul'
    - '/var/run/zuul-merger'
    - '/var/lib/zuul'
    - '/var/lib/zuul/git'
    - '/var/lib/zuul/www'
    - '/var/lib/zuul/www/lib'

- name: Create zuul service file
  become: yes
  become_method: sudo
  file:
    src="{{ item.src }}"
    owner=root
    group=root
    mode=0555
    dest="{{ item.dest }}"
  with_items:
    - { src: 'zuul.init', dest: '/etc/init.d/zuul' }
    - { src: 'zuul-merger.init', dest: '/etc/init.d/zuul-merger' }
    - { src: 'zuul-launcher.init', dest: '/etc/init.d/zuul-launcher' }

- include: zuul-merger.yml
