- include: packages.yml
- include: user.yml

- name: Clone Zuul repository
  become: yes
  git:
    repo=https://git.openstack.org/openstack-infra/zuul
    dest=/opt/zuul

- name: Install Zuul
  become: yes
  pip:
    name=/opt/zuul

- include: config.yml

- name: Create zuul service files
  become: yes
  copy:
    src="{{ item.src }}"
    owner=root
    group=root
    mode=0755
    dest="{{ item.dest }}"
  with_items:
    - { src: 'zuul-server.service', dest: '/etc/systemd/system/zuul-server.service' }
    - { src: 'zuul-server.init', dest: '/etc/init.d/zuul-server' }
    - { src: 'zuul-merger.service', dest: '/etc/systemd/system/zuul-merger.service' }
    - { src: 'zuul-merger.init', dest: '/etc/init.d/zuul-merger' }
    - { src: 'zuul-launcher.service', dest: '/etc/systemd/system/zuul-launcher.service' }
    - { src: 'zuul-launcher.init', dest: '/etc/init.d/zuul-launcher' }

- name: Start Zuul services (server, launcher and merger)
  become: yes
  service:
    name="{{ item }}"
    state=started
    enabled=yes
  with_items:
    - 'zuul-server'
    - 'zuul-merger'
    - 'zuul-launcher'

# Optional includes
# -----------------

- include: layout.yml
  when: zuul_layout is defined

- include: status_page.yml
  when: status_page is defined and status_page
